FROM fsharp:4.1.34

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget \
    && wget https://github.com/fsprojects/Paket/releases/download/5.155.0/paket.exe \
    && chmod a+r paket.exe && mv paket.exe /usr/local/lib/ \
    && printf '#!/bin/sh\nexec /usr/bin/mono /usr/local/lib/paket.exe "$@"' >> /usr/local/bin/paket \
    && chmod u+x /usr/local/bin/paket
ENTRYPOINT ["paket"]

# RUN paket install
